[fonts."Berkeley Mono Nerd font"]
family = "BerkeleyMono Nerd Font"

[fonts.CommitMono]
family = "CommitMono"

[fonts.Default]
family = "Default"

[fonts."Fira Code"]
family = "Fira Code"

[fonts."Geist Mono"]
family = "Geist Mono"
weight = 500

[fonts.Hack]
family = "Hack"

[fonts."IBM Plex Mono"]
family = "IBM Plex Mono"
weight = 450


[fonts."MD IO Trial"]
family = "MD IO Trial"

[fonts.Menlo]
family = "Menlo"

[fonts."Rec Mono"]
family = "Rec Mono Duotone"

[fonts."Roboto Mono"]
family = "Roboto Mono"
