allow_remote_control yes
listen_on unix:/tmp/mykitty

font_size 14
disable_ligatures always
modify_font cell_height 140%

cursor_blink_interval 0
scrollback_lines 10000
scrollbar never

copy_on_select yes
strip_trailing_spaces smart

# hide_window_decorations titlebar-only
macos_titlebar_color background
confirm_os_window_close 0
notify_on_cmd_finish never
enable_audio_bell no
window_alert_on_bell no
command_on_bell none

shell_integration no-title
window_title_template "{title}"

remember_window_size  yes
remember_window_position yes
placement_strategy center
window_padding_width 5
tab_bar_edge bottom
tab_bar_style powerline
# tab_powerline_style round

macos_option_as_alt yes
macos_quit_when_last_window_closed yes
macos_thicken_font 0.2
macos_colorspace displayp3

kitty_mod cmd

map ctrl+k kitten themes --reload-in=all --config-file-name=theme.conf
map ctrl+f kitten choose-fonts --reload-in=all --config-file-name=font.conf
map ctrl+b launch --type=overlay ~/dotfiles/kitty/scripts/update-bg.zsh
map kitty_mod+k launch --type=overlay ~/dotfiles/kitty/scripts/project-picker.zsh

enabled_layouts splits:split_axis=horizontal,stack

map kitty_mod+shift+\ launch --location=hsplit --cwd=current
map kitty_mod+\ launch --location=vsplit --cwd=current
map kitty_mod+t new_tab_with_cwd

map opt+down neighboring_window down
map opt+up neighboring_window up
map opt+left neighboring_window left
map opt+right neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM opt+down
map --when-focus-on var:IS_NVIM opt+up
map --when-focus-on var:IS_NVIM opt+left
map --when-focus-on var:IS_NVIM opt+right

map opt+shift+left resize_window narrower
map opt+shift+right resize_window wider
map opt+shift+up resize_window taller
map opt+shift+down resize_window shorter 3
map opt+shift+0 resize_window reset

map kitty_mod+enter toggle_layout stack

map kitty_mod+equal  change_font_size all +0.5
map kitty_mod+minus  change_font_size all -0.5
map kitty_mod+0      change_font_size all 0

map kitty_mod+shift+,   load_config_file

include theme.conf
include font.conf
include local.conf