gui:
  scrollHeight: 5
  sidePanelWidth: 0.2
  expandFocusedSidePanel: true
  enlargedSideViewLocation: top
  showListFooter: false
  showCommandLog: false
  showPanelJumps: false
  showFileIcons: false

git:
  paging:
    colorArg: always
    pager: >
      delta 
      -s
      --dark
      --true-color always 
      --paging=never
      --syntax-theme base16-256
      --hunk-header-style=omit 
      --file-style=omit
      --line-numbers-right-format={np:^4}
      --line-numbers-left-format={nm:^4}
      --minus-style="red #340F0F"
      --minus-emph-style="red #340F0F"
      --minus-non-emph-style="red #340F0F"
      --plus-style="green #172617"
      --plus-emph-style="green #172617"
      --plus-non-emph-style="green #172617"
      --line-numbers-minus-style="red"
      --line-numbers-plus-style="green"

notARepository: skip
